// Generated by ts-to-zod
import { z } from "zod";

export const transportSchema = z.union([z.literal("JSONRPC"), z.literal("GRPC"), z.literal("HTTP+JSON")]);

export const agentInterfaceSchema = z.object({
    url: z.string(),
    protocolBinding: z.string(),
    tenant: z.string().optional(),
    protocolVersion: z.string()
});

export const agentProviderSchema = z.object({
    url: z.string(),
    organization: z.string()
});

export const agentCardSignatureSchema = z.object({
    protected: z.string(),
    signature: z.string(),
    header: z.any().optional()
});

export const agentExtensionSchema = z.object({
    uri: z.string().optional(),
    description: z.string().optional(),
    required: z.boolean().optional(),
    params: z.any().optional()
});

export const apiKeySecuritySchemeSchema = z.object({
    description: z.string().optional(),
    location: z.union([z.literal("query"), z.literal("header"), z.literal("cookie")]),
    name: z.string()
});

export const httpAuthSecuritySchemeSchema = z.object({
    description: z.string().optional(),
    scheme: z.string(),
    bearerFormat: z.string().optional()
});

export const openIdConnectSecuritySchemeSchema = z.object({
    description: z.string().optional(),
    openIdConnectUrl: z.string()
});

export const mutualTlsSecuritySchemeSchema = z.object({
    description: z.string().optional()
});

export const authorizationCodeOAuthFlowSchema = z.object({
    authorizationUrl: z.string(),
    tokenUrl: z.string(),
    refreshUrl: z.string().optional(),
    scopes: z.record(z.string(), z.string()),
    pkceRequired: z.boolean().optional()
});

export const clientCredentialsOAuthFlowSchema = z.object({
    tokenUrl: z.string(),
    refreshUrl: z.string().optional(),
    scopes: z.record(z.string(), z.string())
});

export const deviceCodeOAuthFlowSchema = z.object({
    deviceAuthorizationUrl: z.string(),
    tokenUrl: z.string(),
    refreshUrl: z.string().optional(),
    scopes: z.record(z.string(), z.string())
});

export const agentCapabilitiesSchema = z.object({
    streaming: z.boolean().optional(),
    pushNotifications: z.boolean().optional(),
    extensions: z.array(agentExtensionSchema).optional(),
    extendedAgentCard: z.boolean().optional()
});

export const oAuthFlowsSchema = z.union([z.object({
        authorizationCode: authorizationCodeOAuthFlowSchema
    }), z.object({
        clientCredentials: clientCredentialsOAuthFlowSchema
    }), z.object({
        deviceCode: deviceCodeOAuthFlowSchema
    })]);

export const oAuth2SecuritySchemeSchema = z.object({
    description: z.string().optional(),
    flows: oAuthFlowsSchema,
    oauth2MetadataUrl: z.string().optional()
});

export const securitySchemeSchema = z.union([z.object({
        apiKeySecurityScheme: apiKeySecuritySchemeSchema
    }), z.object({
        httpAuthSecurityScheme: httpAuthSecuritySchemeSchema
    }), z.object({
        oauth2SecurityScheme: oAuth2SecuritySchemeSchema
    }), z.object({
        openIdConnectSecurityScheme: openIdConnectSecuritySchemeSchema
    }), z.object({
        mtlsSecurityScheme: mutualTlsSecuritySchemeSchema
    })]);

export const agentSkillSchema = z.object({
    id: z.string(),
    name: z.string(),
    description: z.string(),
    tags: z.array(z.string()),
    examples: z.array(z.string()).optional(),
    inputModes: z.array(z.string()).optional(),
    outputModes: z.array(z.string()).optional(),
    securityRequirements: z.array(securitySchemeSchema).optional()
});

export const agentCardSchema = z.object({
    name: z.string(),
    description: z.string(),
    supportedInterfaces: z.array(agentInterfaceSchema),
    provider: agentProviderSchema.optional(),
    version: z.string(),
    documentationUrl: z.string().optional(),
    capabilities: agentCapabilitiesSchema,
    securitySchemes: z.record(z.string(), securitySchemeSchema).optional(),
    securityRequirements: z.array(z.record(z.string(), z.array(z.string()))).optional(),
    defaultInputModes: z.array(z.string()),
    defaultOutputModes: z.array(z.string()),
    skills: z.array(agentSkillSchema),
    signatures: z.array(agentCardSignatureSchema).optional(),
    iconUrl: z.string().optional().nullable()
});
